apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
  namespace: default
spec:
  type: LoadBalancer  # Use ClusterIP for internal access
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
    - name: spark
      port: 7077
      targetPort: 7077
  selector:
    app: spark
    role: master