apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: default
  labels:
    app: spark
    role: worker
spec:
  replicas: 3  # Three worker nodes
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      containers:
        - name: spark-worker
          image: "acrdlspark.azurecr.io/spark_20250331:latest"
          imagePullPolicy: Always
          command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "$(SPARK_MASTER)"]
          ports:
            - containerPort: 8081  # Spark Worker UI
              name: webui
          env:
            - name: SPARK_MODE
              value: "worker"
            - name: SPARK_MASTER
              value: "spark://spark-master-service:7077"  # Connect to the master
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 5
          volumeMounts:
            - name: spark-events
              mountPath: /mnt/data/spark-events # Mount the events volume for event logs
      volumes:
        - name: spark-events
          persistentVolumeClaim:
            claimName: spark-data-pvc  # PVC for event logs