apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  hostPath:
    path: "/mnt/data/spark-events" 